### ISSUE TITLE
[Question] Roadmap, design plans

### ISSUE THREAD

**Issue by Polish-Civil** [Hadyn/runite#16]
Hello, im quite curious as to what dependencies for rendering and other game engine parts this project is about to use, as well as the runescape specific parts, is it going to be 1:1 rewrite based on the runescape code, or is it going to be aimed to be 'conscious' rewrite.

**Comment by Hadyn** [comment]
Hi Polish, 

* Runite uses [Amethyst](https://github.com/amethyst) as its game engine. The renderer will use the [Rendy](https://github.com/amethyst/rendy) module from Amethyst with some modifications.
* Most of the client is and will be "conscious" rewrites of the Runescape engine. For what I have done or planned thus far, I have goals in mind like "determine where assets are stored" and refer to the mechanisms in the Runescape engine to at least achieve a similar purpose but I do not look at the code and translate directly. The only time I refer to the Runescape client is to look up protocols and or file formats.

 We have just started this project almost a month ago and have not started our roadmap, but it's on our radar (see the projects section but it obviously isn't populated right now or meaningful). 

We have a [Discord](https://discord.gg/DbXJCE) that you can join if you'd like to discuss more. Thanks for the questions! If you have any more I'd love to answer them.

**Comment by based64god** [comment]
There is probably some value in adding a roadmap to the wiki/readme at some point, but the project is still in very early stages. We will definitely consider it as we get closer to having stable releases, but it likely won't be for a while. Thanks @Polish-Civil .

**Comment by Hadyn** [comment]
Although this is closed I just want to make the comment that we are looking for people to help out so if this is something you're interested in talking to us more about we'd love to accommodate that.
